### PR TITLE
fix: display real weather data instead of hardcoded values

### LINKED ISSUE #195: Hardcoded weather data.
Image

### PR DESCRIPTION
**Pull request by clrke**
## Summary
Fixes the hardcoded weather data issue in the weather page by displaying actual data from the OpenWeatherMap API.

## Changes
- Added `humidity`, `windSpeed`, `pressure`, and `visibility` fields to the `WeatherData` type
- Updated `fetchWeatherData` function to retrieve and return these additional fields from the API
- Modified the weather page component to display actual data instead of hardcoded values
- Wind speed is converted from m/s to km/h for better readability
- Visibility is converted from meters to kilometers

## Before
Weather details (humidity, wind, pressure, visibility) were showing static hardcoded values:
- Humidity: Always 65%
- Wind: Always 12 km/h
- Pressure: Always 1013 hPa
- Visibility: Always 10 km

## After
Weather details now display real-time data from the OpenWeatherMap API for each city.

Fixes #195

### CODE REVIEW

File: src/types/index.ts [hunk 1]
```diff
@@ -46,6 +46,10 @@ export interface WeatherData {
   temperature: number;
   condition: string;
   icon: string;
+  humidity?: number;
+  windSpeed?: number;
+  pressure?: number;
+  visibility?: number;
```
Comment (angelofallars) [inline src/types/index.ts]: as far as i can tell, [`https://api.bettergov.ph/weather`](https://api.bettergov.ph/weather) does not return any nullable values, see the definition for `WeatherResponseData` in `functions/api/weather.ts`: 
https://github.com/bettergovph/bettergov/blob/6dd79e0fc77fd8af251c02a4ce226c2de312f332/functions/api/weather.ts#L43-L72

so i think these properties don't really need to be optional

**Review by angelofallars — CHANGES_REQUESTED** [review]

File: src/types/index.ts (hunk 1 above)
Comment (clrke) [reply src/types/index.ts]: Thanks for the review! Let me fix this.

**Review by angelofallars — APPROVED** [review]
