### PR TITLE
fix(ui): improve visa quick search and hero section in visa page

### LINKED ISSUE #123: [UX Issue] Visa Page UX Bugs: Search, Padding, and Dropdown Issues
# Visa Page UX Bugs: Search, Padding, and Dropdown Issues

## Bug Description
The visa page has multiple mobile UX issues that impact user experience on mobile and tablet devices.

<div>
    <a href="https://www.loom.com/share/d5aebb18b8894aa7a9e0d3b133bbfa59">
      <p>Visa Page UX Bugs: Search, Padding, and Dropdown Issues</p>
    </a>
    <a href="https://www.loom.com/share/d5aebb18b8894aa7a9e0d3b133bbfa59">
      
    </a>
  </div>

### 1. Non-functional Search Input 🔍
- **Problem**: The "Quick visa check" search input in the hero section doesn't show search results
- **Impact**: Users can type, but can't see what they're searching for or any results
- **Expected**: Search should show filtered country options as the user types
- **Current**: Search input appears to work but provides no visual feedback

### 2. Inconsistent Hero Section Padding 📱
- Problem**: Hero section lacks proper padding across different device sizes
- **Impact**: Content touches screen edges on various devices
- **Affected Devices**:
  - Mobile: Inadequate padding
  - Tablet: No specific tablet padding
  - iPad Pro: No padding at all, content touches edges
- **Expected**: Consistent, appropriate padding for all device sizes

### 3. Missing Dropdown Functionality 📍
- **Problem**: The search input was just a text field with no dropdown or results display
- **Impact**: Users could type, but had no way to see available countries or select from them
- **Expected**: Search should show a dropdown with country options that users can select from
- **Current**: Plain text input with no visual feedback or selection interface

## User Impact
- Mobile users cannot effectively search for countries
- Poor visual experience due to content touching the screen edges
- No way to select countries from search results
- Overall, degraded mobile experience compared to desktop

## Expected Behavior
1. Search input should show real-time filtered results
2. Hero section should have appropriate padding for all device sizes
3. Search should provide a dropdown interface for country selection

## Technical Notes
- Issues affect mobile and tablet breakpoints
- Search functionality exists but lacks UI feedback
- Padding issues span multiple Tailwind breakpoints
- Dropdown positioning needs viewport-aware logic

## Testing Steps
1. **Search Issue**: Test search input in the hero section on mobile
2. **Padding Issue**: Check hero section padding on various devices
3. **Missing Dropdown**: Verify search input has no dropdown or results
4. **Cross-device**: Test on iPhone, Android, iPad, and various screen sizes

## Reproduction Steps
1. Open the visa page on a mobile device
2. Try to use the search input in the hero section - notice that no dropdown appears
3. Type in search input - notice no results or feedback
4. Check if the content touches the screen edges on different devices
5. Verify all issues occur consistently across mobile devices

### PR DESCRIPTION
**Pull request by iyanski**
## Add mobile-friendly country selector for visa requirements page

- Replace desktop-only search input with responsive SelectPicker component in hero section
- Implement a searchable dropdown for country selection on mobile/tablet devices  
- Maintain existing desktop functionality with the country list sidebar
- Add proper accessibility attributes and keyboard navigation
- Ensure consistent UX across all screen sizes

**Changes:**
- Created new `SelectPicker` component with search, clear, and positioning features
- Updated hero section to use responsive search (desktop input + mobile SelectPicker)
- Updated main content area to use SelectPicker on mobile/tablet (xl:hidden)
- Preserved desktop search input for larger screens (hidden xl:block)
- Added proper TypeScript interfaces and a responsive design
- Fixes to lint issues

Closes #123

BetterGov_ph _ Republic of the Philippines _ Community Powered Government Portal · 10 25pm · 09-20

BetterGov_ph _ Republic of the Philippines _ Community Powered Government Portal · 10 24pm · 09-20

**No changes made in the desktop view**

BetterGov_ph _ Republic of the Philippines _ Community Powered Government Portal · 10 26pm · 09-20

### CODE REVIEW

File: src/components/ui/SelectPicker.tsx [hunk 1]
```diff
@@ -0,0 +1,279 @@
...
+    window.addEventListener('scroll', handleScroll, true);
+
+    return () => {
+      document.removeEventListener('mousedown', handleClickOutside);
+      window.removeEventListener('resize', handleResize);
+      window.removeEventListener('scroll', handleScroll, true);
+    };
+  }, [isOpen]);
+
+  const sizes = {
```
Comment (mikkotan) [inline src/components/ui/SelectPicker.tsx:160]: **nit (non-blocking)**: do we need this defined inside the component?

**Review by mikkotan — APPROVED** [review]

**Review by angelofallars — CHANGES_REQUESTED** [review]
merge conflict on `iyanski:bugfix/visa-page-country-selector-mobile`

File: src/components/ui/SelectPicker.tsx (hunk 1 above)
Comment (iyanski) [reply src/components/ui/SelectPicker.tsx:160]: You're right to think about this. This is a strong use case for creating component-specific size utilities. For example

``
export const buttonSizes = {
  sm: 'text-sm px-3 py-1.5 h-8',
  md: 'text-base px-4 py-2 h-10', 
  lg: 'text-lg px-6 py-3 h-12',
} as const;

export const inputSizes = {
  sm: 'h-9 text-sm',
  md: 'h-11 text-base',
  lg: 'h-14 text-lg', 
} as const;
```
