### PR TITLE
fix: (services) Scroll to Top Upon Clicking a Category or Subcategory

### LINKED ISSUE #431: Services: Not Scrolling to Top Upon Clicking a Category or Sub-category
## Description

Upon clicking a category or subcategory in the Sidebar, the contents will be filtered, but the view is still at the bottom of the page. This is also happening when clicking the category or subcategory in a Service's card.

## Steps to Reproduce

1. Go to https://bettergov.ph/services
2. Scroll down until a lot of data has been loaded.
3. Click the category or sub-category.

## Suggested Behaviour

Upon clicking a category or subcategory, the page should be scrolled to the top to view the actual content.

## Actual Behaviour

🐛 The new filtered content is loaded, but the view is still at the bottom of the page instead of the top.

## Screen Recording

https://github.com/user-attachments/assets/6db40fa2-355d-473f-abad-b4bb0aea9721

### PR DESCRIPTION
**Pull request by boringdeveloper**
## Overview

This PR closes #431 by making sure that the page is scrolled to the top when a category or subcategory is clicked.

## Changes

- Added a `scrollToTop` function in `scrollUtils.ts`
- Use the `scrollToTop` function in the category or subcategory `onClick` event.

## Testing

Tested locally.

_Page is scrolled to the top when a category or subcategory is clicked._

[Services scroll to top issue fix.webm](https://github.com/user-attachments/assets/147b423a-1f8c-45a7-bfc0-0a832417f387)

### CODE REVIEW

**Comment by KishonShrill** [comment]
If you're done with the work @boringdeveloper, ping me and I'll have it squashed and merged to main

File: src/pages/services/index.tsx [hunk 1]
```diff
@@ -356,6 +357,7 @@ export default function ServicesPage() {
                     <div role='listitem'>
                       <button
                         onClick={() => {
+                          scrollToTop();
```
Comment (niculistana) [inline src/pages/services/index.tsx:360]: Let us know if it's possible to do a `useEffect` here. But feel free to ship the refactor later:

```ts
useEffect((
) => {
   // other logic
   // check if it's not the same category or subcategory
   scrollToTop();
   setSidebarOpen(false);
}, [searchQuery, selectedCategory, selectedSubcategory])
```

Comment (boringdeveloper) [reply src/pages/services/index.tsx:360]: Cool, happy to explore this idea in a separate PR 👍🏽

**Comment by boringdeveloper** [comment]
> If you're done with the work @boringdeveloper, ping me and I'll have it squashed and merged to main

@KishonShrill , I'm done with the work for this one. I'll work on nicu's suggestion in a separate PR.
Feel free to merge whenever you have the chance, thank you 🙏🏽

**Comment by KishonShrill** [comment]
> > If you're done with the work @boringdeveloper, ping me and I'll have it squashed and merged to main
> 
> @KishonShrill , I'm done with the work for this one. I'll work on nicu's suggestion in a separate PR.
> Feel free to merge whenever you have the chance, thank you 🙏🏽 

Alrighty, I'll merge it when I get back from work. Says can't merge on the phone app, gonna have to check why later.
