### PR TITLE
Fix BIR links leading to 404 pages

### LINKED ISSUE #344: [BUG] 404 page on BIR links in Services > Tax > View Services
<h3>Description: </h3>

BIR links in Services > Tax page lead to 404 page
 
Services > Tax > File Tax Complaints 'View Service'
Goes to https://www.bir.gov.ph/index.php/eservices/ecomplaint-home.html

Services > Tax > Apply for BIR Tax Clearance Certificate "View Service"
Goes to https://www.bir.gov.ph/index.php/tax-clearance/tax-clearance-application-form.html

Services > Tax > Register for a Taxpayer Identification Number (TIN) "View Service"
Goes to https://www.bir.gov.ph/index.php/registration-requirements/primary-registration/application-for-tin.html

<h3>Expected behavior:</h3>

- go to eComplaint webpage, BIR Tax Clearance certificate, or registration for TIN page.

**Actual behavior:**

- leads to 404 page

<h3>Screenshots:</h3>

Image

**4 possible eComplaint destinations:**

1. https://revie.bir.gov.ph/ecomplaint-disiplina 
(BIR staff)
2. https://revie.bir.gov.ph/ecomplaint-no-or 
(non-issuance of OR)
3. https://revie.bir.gov.ph/ecomplaint-rate 
(tax evasion/avoidance)
4. https://revie.bir.gov.ph/ecomplaint-others 
(tax related others)

Possible tax clearance destination:
https://tcsfo.bir.gov.ph/

Possible tin registration destination:
https://orus.bir.gov.ph/

### PR DESCRIPTION
**Pull request by Polqt**
**Description**
Fixes the 404 errors on BIR links in Services > Tax > View Services by updating URLs to correct working destinations.

**Changes Made**
- **Apply for BIR Tax Clearance Certificate**: Updated URL to `https://tcsfo.bir.gov.ph/`
- **Register for a Taxpayer Identification Number (TIN)**: Updated URL to `https://orus.bir.gov.ph/`
- **File Tax Complaints**: Replaced single service with 4 specific complaint services:
  - File Complaint Against BIR Staff → `https://revie.bir.gov.ph/ecomplaint-disiplina`
  - File Complaint for Non-Issuance of Official Receipt → `https://revie.bir.gov.ph/ecomplaint-no-or`
  - File Complaint for Tax Evasion/Avoidance → `https://revie.bir.gov.ph/ecomplaint-rate`
  - File Other Tax Related Complaints → `https://revie.bir.gov.ph/ecomplaint-others`

**Issue**
Closes #344 - [BUG] 404 page on BIR links in Services > Tax > View Services

### CODE REVIEW

**Comment by niculistana** [comment]
Hi @Polqt  thank you for the pull request.

Here are the next steps:

Check your review app [review app](https://bettergov-git-review-fixbir-links-404-adobocorp.vercel.app).
Reach out to #quality and have them test.
Once  QA has reviewed the app, please tag me on discord(nicu_02078).

File: e2e/utils/navbar.ts [hunk 1]
```diff
@@ -43,6 +43,10 @@ export async function navigate(
   // For desktop
   if (option) {
     await page.getByRole('link', { name: option, exact: true }).first().hover();
+    await page.waitForSelector('div.absolute.left-0.mt-2.w-56', {
+      state: 'visible',
+      timeout: 2000,
+    });
```
Comment (DaijobuDes) [inline e2e/utils/navbar.ts]: Using [waitForSelector()](https://playwright.dev/docs/api/class-page#page-wait-for-selector) is apparently highly discouraged according on the playwright docs.

And apparently I tested this on a headless system (like how the CI would work), will still cause an error specifically for firefox.

image

On windows, it does pass for some reason 

(this has been an issue for a while now)

File: e2e/navigation.spec.ts [hunk 2]
```diff
@@ -15,7 +15,9 @@ test.describe('Navigation', () => {
       ).toBeVisible();
     } else {
       await expect(
-        page.getByRole('menuitem', { name: 'About the Philippines' })
+        page
+          .locator('div.absolute.left-0.mt-2.w-56')
+          .filter({ hasText: 'About the Philippines' })
```
Comment (DaijobuDes) [inline e2e/navigation.spec.ts]: related to other comment (this can be reverted)

**Comment by niculistana** [comment]
Screenshot 2025-09-30 at 10 40 31 PM

**Review by niculistana — APPROVED** [review]

**Review by niculistana — APPROVED** [review]
