### PR TITLE
fix(services): Services Pagination to Infinite Scrolling

### LINKED ISSUE #382: Load More button does not scroll to top after replacing content
## Description
When clicking the **Load More** button, the content is replaced with a new set of data. However, the scroll position stays at the bottom of the container, leaving the user at the end of the new content.

## Steps to Reproduce
1. Go to https://bettergov.ph/services?category=business-trade
2. Scroll to the bottom of the list.  
3. Click **Load More**.  
4. Observe that the new content loads, but the view remains at the bottom instead of the top.  

## Suggested Behavior
After clicking **Load More**, the container should automatically scroll back to the top so users can immediately view the newly loaded content.

https://github.com/user-attachments/assets/56df1730-e56d-4938-9469-92eb74ce000c

### PR DESCRIPTION
**Pull request by boringdeveloper**
## Overview

This PR closes #382 by implementing infinite scrolling for the services pagination instead of replacing the current content.

## Changes

- Replaced the "Load More Services" `<button>` with an invisible `<div>` that serves as the trigger.
- `paginatedServices` splicing changed to simply start with index `0` to append new content instead of replacing the current ones.
- Created a `loadMoreRef` using `useRef` to track when the user scrolls near the bottom of the services list. 
- Added a `useEffect` hook that creates an Intersection Observer to automatically trigger loading more services when the user scrolls within `100px` of the trigger element.
- 🆕 Removed `page=` query parameter in the URL.

## Testing

Tested locally.

_Infinite scrolling is working as expected to load more content._

https://github.com/user-attachments/assets/bd30bafe-3220-43a6-97ea-f6fedcba6d3d

### CODE REVIEW

File: src/pages/services/index.tsx [hunk 1]
```diff
@@ -145,6 +155,57 @@ export default function ServicesPage() {
...
+      filteredServices.length <= currentPage * ITEMS_PER_PAGE
+    ) {
+      return;
+    }
+
+    setIsLoadingMore(true);
+
+    // Ensure the loading state is rendered
+    // before the page number is incremented
+    requestAnimationFrame(() => {
```
Comment (niculistana) [inline src/pages/services/index.tsx]: Hmmm I am curious why this method is here? I tried removing it locally and there seems to be no difference.

Comment (boringdeveloper) [reply src/pages/services/index.tsx]: Yes, removing it would still make the infinite scrolling work as expected because the infinite scrolling only needs the Intersection Observer and `setCurrentPage`.

The `requestAnimationFrame` here is used for visual timing, ensuring that users see the loading state before new content appears.

Actually, looking at it again... it can be simplified further to:

```ts
setIsLoadingMore(true);
requestAnimationFrame(() => {
  setCurrentPage(prev => prev + 1);
  setIsLoadingMore(false);
});
```

I added the nested `requestAnimationFrame` to make sure that the user can see the loading spinner while the new content is being rendered. But it probably isn't necessary 😅

Comment (boringdeveloper) [reply src/pages/services/index.tsx]: Or do you reckon we simply remove the `requestAnimationFrame` and `isLoadingMore` implementation since the data is fetched from static JSON files, the fetching is instantaneous, and there's no real "loading" happening? The `requestAnimationFrame` and `isLoadingMore` are unnecessary overhead in this case.

Comment (boringdeveloper) [reply src/pages/services/index.tsx]: I have updated this with a simplified implementation instead.

Comment (niculistana) [reply src/pages/services/index.tsx]: @boringdeveloper Yes mostly suggested it as we're not fetching data externally. Thanks for taking the time to explain how it works!

**Comment by niculistana** [comment]
Hi @boringdeveloper thank you for the pull request. I tested locally and have taken a look at the code and it looks good!

Here are the next steps:

Check your review app [review app](https://bettergov-git-fix-382services-scroll-adobocorp.vercel.app/services).
Reach out to #quality and have them test.
Once QA has reviewed the app, please tag me on discord(nicu_02078).

**Comment by niculistana** [comment]
Ah please use https://bettergov-git-fix-382services-scroll-adobocorp.vercel.app/ and ask #quality team to navigate to the services page.

**Review by DaijobuDes — COMMENTED** [review]
Sent feedback on #quality channel

Reference: https://discord.com/channels/1415670958710325270/1419325350550179861/1425007991400431719

**Comment by boringdeveloper** [comment]
@DaijobuDes, I have removed the page number in the URL.

[Infinite Scroll.webm](https://github.com/user-attachments/assets/9df82fd3-39d0-4fb4-8415-0a2c41745a28)
