### PR TITLE
fix(footer): update Discord link

### LINKED ISSUE #356: Expired Discord Invite Link in Footer
**Description:**

The Discord invite link in the footer of the BetterGov.ph website appears to be expired. Clicking the link leads to an error page stating that the invite is invalid or has expired.

**Steps to Reproduce:**

1. Scroll to the bottom of any page on BetterGov.ph..
2. Click the Discord icon or invite link.
3. Observe the error message from Discord.

**Expected Behavior:** 
The link should direct users to an active Discord server invite.

**Suggested Fix:** 
Update the footer with a valid, non-expiring Discord invite link or implement a dynamic system to refresh the link periodically.

**Additional Context:** 
This issue may hinder community engagement and discourage new contributors from joining discussions.

### PR DESCRIPTION
**Pull request by melio0504**
### Description
This PR updates the Discord link in the website footer. The previous link was outdated, preventing users from joining the community directly. This update ensures visitors are redirected to the correct and active Discord invite.

Fixes #356

### Changes Made
- Updated the footer’s Discord link to the official and active invite URL.

### CODE REVIEW

File: src/data/navigation.ts [hunk 1]
```diff
@@ -114,7 +114,7 @@ export const footerNavigation = {
   ],
   socialLinks: [
     { label: 'Facebook', href: 'https://facebook.com/bettergovph' },
-    { label: 'Discord', href: '/discord' },
+    { label: 'Discord', href: 'https://discord.gg/bettergovph' },
```
Comment (DaijobuDes) [inline src/data/navigation.ts]: The old invite link is in this file, but if this is changed directly to a discord invite link then wouldn't be this file no longer useful?

https://github.com/bettergovph/bettergov/blob/a5855c21175307ce289228707b80494f6c69d29c/src/pages/Discord.tsx#L5

Comment (melio0504) [reply src/data/navigation.ts]: I noticed that using `href="/discord"` in the footer points to an expired invite link.

image 

Also, the Discord.tsx file only performs a quick redirect for a split second, which isn’t even visible to the user. Because of this, it no longer serves a useful purpose.


https://github.com/user-attachments/assets/28d533e8-7da1-499e-9c97-6c647facb41a

**Comment by melio0504** [comment]
Sorry about the earlier mistake. I removed Discord.tsx thinking it wasn’t needed, but it turns out the site broke because the footer relies on it. This PR brings Discord.tsx back and just updates the invite link inside it so everything works again.

**Comment by Sheape** [comment]
LGTM. Thank you so much for your contribution @melio0504 and also thanks for @DaijobuDes for reviewing this beforehand.

**Review by Sheape — APPROVED** [review]
